build:
  maxIssues: 0
  excludeCorrectable: true

config:
  validation: true

processors:
  active: true

style:
  MagicNumber:
    active: true
    ignoreNumbers: ["-1", "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "24", "30", "60", "100"]
  MagicString:
    active: false
  WildcardImport:
    active: true
    excludeImports: ["java.time.*"]
  MaxLineLength:
    active: true
    maxLineLength: 140

naming:
  PackageNaming:
    active: true
    packagePattern: '[a-z]+(\.[a-z][a-z0-9_]*)*'

performance:
  SpreadOperator:
    active: false

coroutines:
  GlobalCoroutineUsage:
    active: true

complexity:
  LongParameterList:
    active: true
    threshold: 6
  TooManyFunctions:
    active: false

exceptions:
  TooGenericExceptionThrown:
    active: false
